// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StickerFire.Data;
using StickerFire.Models;
using System;

namespace StickerFire.Migrations.StickerFireDb
{
    [DbContext(typeof(StickerFireDbContext))]
    [Migration("20171116002948_stickerFire")]
    partial class stickerFire
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StickerFire.Models.Campaign", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("Category");

                    b.Property<string>("DenyMessage");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400);

                    b.Property<DateTime>("Expiration");

                    b.Property<string>("ImgPath");

                    b.Property<string>("OwnerID");

                    b.Property<bool>("Published");

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<int>("Views");

                    b.Property<int>("Votes");

                    b.HasKey("ID");

                    b.ToTable("Campaign");
                });
#pragma warning restore 612, 618
        }
    }
}
